---

- hosts: all
  become: true
  tasks:

  - name: update repo
    apt:
      update_cache: yes

  - name: install apache2
    apt:
      name: apache2
      state: absent

  - name: install PHP
    apt:
      name: libapache2-mod-php
      state: absent
